name: Release

# Triggered on every push to main.
# Only proceeds when the commit is a merged release PR, identified by the
# "chore(release): vX.Y.Z" message written by scripts/release.sh.
#
# CHANGELOG.md is already committed locally — CI only tags and creates the release.

pipeline:
  tag-and-release:
    image: alpine:latest
    commands:
      - apk add --no-cache git bash curl jq
      - |
        set -euo pipefail

        # Extract version from commit message ("chore(release): vX.Y.Z")
        VERSION=$(echo "${CI_COMMIT_MESSAGE}" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?' | head -n1 || true)

        if [[ -z "$VERSION" ]]; then
          echo "No version found in commit message — not a release commit, skipping"
          exit 0
        fi

        echo "→ Release detected: ${VERSION}"

        # Generate release notes for this version only (release body)
        RELEASE_NOTES=$(awk -v ver="$VERSION" '
          /^## / { if (found) exit; if (index($0, ver)) found=1 }
          found  { print }
        ' CHANGELOG.md)

        # Push tag
        git config user.name  "woodpecker[bot]"
        git config user.email "woodpecker@localhost"
        git remote set-url origin "https://${GITEA_TOKEN}@codeberg.org/${CI_REPO_OWNER}/${CI_REPO_NAME}.git"
        git tag "$VERSION"
        git push origin "$VERSION"
        echo "✓ Tag ${VERSION} pushed"

        # Create Gitea release
        IS_PRERELEASE="false"
        [[ "$VERSION" == *"-"* ]] && IS_PRERELEASE="true"

        BODY=$(printf '%s' "$RELEASE_NOTES" | jq -Rs .)

        curl -sSf -X POST \
          "https://codeberg.org/api/v1/repos/${CI_REPO_OWNER}/${CI_REPO_NAME}/releases" \
          -H "Authorization: token ${GITEA_TOKEN}" \
          -H "Content-Type: application/json" \
          -d "{
            \"tag_name\": \"${VERSION}\",
            \"name\": \"Release ${VERSION}\",
            \"body\": ${BODY},
            \"draft\": false,
            \"prerelease\": ${IS_PRERELEASE}
          }"

        echo "✓ Release ${VERSION} created on Codeberg"
    secrets:
      - source: gitea_token
        target: GITEA_TOKEN
    when:
      - event: push
        branch: main
